export const ROLES_KEY = '__ROLES_KEY__'
export const IS_PUBLIC_KEY = '__IS_PUBLIC_KEY__'

export const WHERE_OPTION_METADATA = 'WHERE_OPTION_METADATA'
export const WHERE_OPTION_TYPE_METADATA = 'WHERE_OPTION_TYPE_METADATA'
