name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Staging
        uses: Techie-Pi/node-vps-deployment@main
        with:
          remote-path: "~/app/mall-service"
          host: 121.5.165.149
          username: "root"
          password: ${{ secrets.SSH_PASSWORD }}
          pm2-id: "mall-service"
